# Generated by Django 4.2.8 on 2025-08-03 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', max_length=2)),
                ('has_specific_idea', models.BooleanField(default=True)),
                ('has_initial_concept', models.BooleanField(blank=True, null=True)),
                ('initial_concept', models.TextField(blank=True, null=True)),
                ('program_name', models.CharField(blank=True, max_length=255, null=True)),
                ('general_idea', models.TextField(blank=True, null=True)),
                ('target_audience', models.TextField(blank=True, null=True)),
                ('program_objectives', models.TextField(blank=True, null=True)),
                ('program_type', models.CharField(blank=True, max_length=255, null=True)),
                ('program_duration', models.CharField(blank=True, max_length=255, null=True)),
                ('episode_count', models.CharField(blank=True, max_length=50, null=True)),
                ('filming_location', models.TextField(blank=True, null=True)),
                ('current_step', models.CharField(default='start', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdeaResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_type', models.CharField(choices=[('suggestions', 'Suggestions'), ('discussion_questions', 'Discussion Questions'), ('missing_data', 'Missing Data Proposals'), ('program_format', 'Program Format'), ('program_script', 'Program Script'), ('visual_materials', 'Visual Materials')], max_length=50)),
                ('content', models.TextField()),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='program_ideation.programidea')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
