# Generated by Django 4.2.8 on 2025-08-06 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program_ideation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(choices=[('program_name', 'Program Name'), ('general_idea', 'General Idea'), ('target_audience', 'Target Audience'), ('program_objectives', 'Program Objectives'), ('program_type', 'Program Type'), ('program_duration', 'Program Duration'), ('episode_count', 'Episode Count'), ('filming_location', 'Filming Location')], max_length=50)),
                ('note_content', models.TextField(help_text='Note or request for enhancement')),
                ('response_content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('is_applied', models.BooleanField(default=False, help_text='Whether the suggestion has been applied')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='program_ideation.programidea')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
