# Generated by Django 4.2.8 on 2025-08-06 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program_ideation', '0002_ideanote'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideanote',
            name='note_type',
            field=models.CharField(choices=[('enhancement', 'Enhancement'), ('question', 'Question'), ('concern', 'Concern')], default='enhancement', max_length=20),
        ),
        migrations.AddField(
            model_name='ideanote',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='ideanote',
            name='field_name',
            field=models.CharField(blank=True, choices=[('program_name', 'Program Name'), ('general_idea', 'General Idea'), ('target_audience', 'Target Audience'), ('program_objectives', 'Program Objectives'), ('program_type', 'Program Type'), ('program_duration', 'Program Duration'), ('episode_count', 'Episode Count'), ('filming_location', 'Filming Location')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='AppliedSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(max_length=50)),
                ('suggestion_text', models.TextField()),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_suggestions', to='program_ideation.ideanote')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(max_length=50)),
                ('current_content', models.TextField(blank=True, null=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_fields', to='program_ideation.ideanote')),
            ],
            options={
                'unique_together': {('note', 'field_name')},
            },
        ),
    ]
