[phases.setup]
nixPkgs = ['python310', 'ffmpeg', 'libsndfile']

[phases.build]
cmds = [
    'pip install --upgrade pip',
    'pip install -r requirements.txt',
    'python manage.py collectstatic --noinput --settings=config.settings.production'
]

[start]
cmd = 'gunicorn config.wsgi:application --bind 0.0.0.0:$PORT'

[variables]
PYTHON_VERSION = '3.10'
DJANGO_SETTINGS_MODULE = 'config.settings.production'