# Generated by Django 4.2.8 on 2025-08-12 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import transcription.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtitleProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], max_length=10)),
                ('subtitle_mode', models.CharField(choices=[('same', 'Same Language'), ('translate', 'Translated')], max_length=20)),
                ('target_language', models.CharField(blank=True, choices=[('ar', 'Arabic'), ('en', 'English')], max_length=10, null=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in minutes', null=True)),
                ('srt_file_arabic', models.FileField(blank=True, null=True, upload_to=transcription.models.subtitle_file_path)),
                ('srt_file_english', models.FileField(blank=True, null=True, upload_to=transcription.models.subtitle_file_path)),
                ('vtt_file_arabic', models.FileField(blank=True, null=True, upload_to=transcription.models.subtitle_file_path)),
                ('vtt_file_english', models.FileField(blank=True, null=True, upload_to=transcription.models.subtitle_file_path)),
                ('doc_file_arabic', models.FileField(blank=True, null=True, upload_to=transcription.models.subtitle_file_path)),
                ('doc_file_english', models.FileField(blank=True, null=True, upload_to=transcription.models.subtitle_file_path)),
                ('processed_video', models.FileField(blank=True, null=True, upload_to=transcription.models.processed_video_path)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=transcription.models.video_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('retention', models.CharField(choices=[('5days', 'Keep for 5 days'), ('delete', 'Delete now')], default='5days', max_length=10)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, help_text='Video duration in seconds', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubtitleStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('font_family', models.CharField(default='Arial', max_length=100)),
                ('font_size', models.IntegerField(default=24, help_text='Font size in pixels')),
                ('font_color', models.CharField(default='#FFFFFF', help_text='Hex color code', max_length=7)),
                ('font_weight', models.CharField(choices=[('normal', 'Normal'), ('bold', 'Bold')], default='normal', max_length=20)),
                ('font_style', models.CharField(choices=[('normal', 'Normal'), ('italic', 'Italic')], default='normal', max_length=20)),
                ('text_align', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=20)),
                ('background_color', models.CharField(default='#000000', help_text='Hex color code', max_length=7)),
                ('background_opacity', models.FloatField(default=0.7, help_text='0 to 1')),
                ('padding', models.IntegerField(default=10, help_text='Padding in pixels')),
                ('border_radius', models.IntegerField(default=5, help_text='Border radius in pixels')),
                ('position_y', models.IntegerField(default=85, help_text='Vertical position as percentage from top')),
                ('text_shadow', models.BooleanField(default=True)),
                ('shadow_color', models.CharField(default='#000000', max_length=7)),
                ('shadow_blur', models.IntegerField(default=2)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='style', to='transcription.subtitleproject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='subtitleproject',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle_projects', to='transcription.videofile'),
        ),
        migrations.CreateModel(
            name='SubtitleSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segment_number', models.IntegerField()),
                ('start_time', models.FloatField(help_text='Start time in seconds')),
                ('end_time', models.FloatField(help_text='End time in seconds')),
                ('original_text', models.TextField()),
                ('translated_text', models.TextField(blank=True, null=True)),
                ('edited_text', models.TextField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='transcription.subtitleproject')),
            ],
            options={
                'ordering': ['segment_number'],
                'unique_together': {('project', 'segment_number')},
            },
        ),
    ]
