# Generated by Django 4.2.8 on 2025-07-17 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0002_alter_question_options_question_sequence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='conversation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='askme.conversation'),
            preserve_default=False,
        ),
    ]
