# Generated by Django 4.2.8 on 2025-08-13 12:26

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('source_language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], max_length=10)),
                ('translation_mode', models.CharField(choices=[('same', 'Same Language'), ('translate', 'Translate')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('video_file', models.FileField(upload_to=core.utils.get_file_upload_path)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranslationOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('output_type', models.CharField(choices=[('srt_original', 'SRT Original'), ('srt_translated', 'SRT Translated'), ('vtt_original', 'VTT Original'), ('vtt_translated', 'VTT Translated'), ('docx_original', 'DOCX Original'), ('docx_translated', 'DOCX Translated'), ('txt_original', 'TXT Original'), ('txt_translated', 'TXT Translated')], max_length=20)),
                ('file', models.FileField(upload_to=core.utils.get_file_upload_path)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='translation.translationproject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.FloatField(help_text='Start time in seconds')),
                ('end_time', models.FloatField(help_text='End time in seconds')),
                ('original_text', models.TextField()),
                ('translated_text', models.TextField(blank=True, null=True)),
                ('sequence', models.IntegerField()),
                ('font_family', models.CharField(default='Arial', max_length=100)),
                ('font_size', models.IntegerField(default=16)),
                ('font_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('background_color', models.CharField(default='#000000', max_length=20)),
                ('background_opacity', models.FloatField(default=0.5)),
                ('is_bold', models.BooleanField(default=False)),
                ('is_italic', models.BooleanField(default=False)),
                ('is_underline', models.BooleanField(default=False)),
                ('alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='translation.translationproject')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
