# Generated by Django 4.2.8 on 2025-09-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='speaker',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
